Multiple workers
Ensembl/ensembl-thoas pull request #132
Opened 2023-10-20 16:14 UTC by sanjay-boddu

Increasing the number of processes because long-running queries are blocking other queries.

2023-10-23 08:35 UTC, bilalebi approved these changes
Looks good to me.
In the future we can consider:
1. Adding [Artillery](https://github.com/artilleryio/artillery) tests for performance testing
2. Implement [auto-scaling](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/).

2023-10-23 09:44 UTC, kamaldodiya requested changes

2023-10-23 09:44 UTC, kamaldodiya commented on k8s/web-prod/base/deployment.yaml
> +            "4",
Would be nice to get the WORKERS from environment variable. this will give flexibility to experiment without modifying the deployment.yaml. You may well keep default value to 4 :)

2023-10-31 11:24 UTC, bilalebi commented on k8s/web-prod/base/deployment.yaml
> +            "4",
@kamaldodiya, I'm thinking of adding `WORKERS` to [configmap.yaml](https://github.com/Ensembl/ensembl-thoas/blob/develop/k8s/web-prod/base/configmap.yaml):
```
apiVersion: v1
data:
  ...
  WORKERS: "4"
...
```
and using it in `deployment.yaml`
```
...
        args:
          - "--host"
          - "0.0.0.0"
          - "--port"
          - "8000"
          - "--workers"
          - "$(WORKERS)" # Assuming WORKERS key is in the thoas-configmap
        envFrom:
        - configMapRef:
            name: thoas-configmap
```
This is what you had in mind right?

2023-10-31 11:34 UTC, kamaldodiya commented on k8s/web-prod/base/deployment.yaml
> +            "4",
Yes, @bilalebi  you are right that is what I had proposed.

2023-10-31 12:24 UTC, kamaldodiya approved these changes

2023-10-31 13:08 UTC, merged